name: buildTest

on:
  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'wire-ios/**'
      
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      ui: ${{ steps.filter.outputs.ui }}
      syncEngine: ${{ steps.filter.outputs.syncEngine }}
      dataModel: ${{ steps.filter.outputs.dataModel }}
      iosSystem: ${{ steps.filter.outputs.iosSystem }}
      requestStrategy: ${{ steps.filter.outputs.requestStrategy }}
      transport: ${{ steps.filter.outputs.transport }}
      shareEngine: ${{ steps.filter.outputs.shareEngine }}
      cryptobox: ${{ steps.filter.outputs.cryptobox }}
      mockTransport: ${{ steps.filter.outputs.mockTransport }}
      notificationEngine: ${{ steps.filter.outputs.notificationEngine }}
      wireImages: ${{ steps.filter.outputs.wireImages }}
      utilities: ${{ steps.filter.outputs.utilities }}
      
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          ui:
            - 'wire-ios/**'
          syncEngine:
            - 'wire-ios-sync-engine/**'
          dataModel:
            - 'wire-ios-data-model/**'
          iosSystem:
            - 'wire-ios-system/**'
          requestStrategy:
            - 'wire-ios-request-strategy/**'
          transport:
            - 'wire-ios-transport/**'
          shareEngine:
            - 'wire-ios-share-engine/**'
          cryptobox:
            - 'wire-ios-cryptobox/**'
          mockTransport:
            - 'wire-ios-mock-transport/**'
          notificationEngine
            - 'wire-ios-notification-engine/**'
          wireImages
            - 'wire-ios-images/**'
          utilities
            - 'wire-ios-utilities/**'  

  build:
    needs: changes
    runs-on: macOS-latest
    
    #outputs:
    #  output1: ${{ steps.step1.outputs.test }}
      
    #outputs:
    #    derivePath: 'ios/wire-ios/build'

    env:
      derivePath: 'ios/wire-ios/build'
      
    steps:
      - uses: actions/checkout@v3
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      
      - name: Select Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
      - name: Fetch dependencies
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./setup.sh

      - name: Build
        run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireDataModel -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireSyncEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          xcodebuild build -workspace wire-ios.xcworkspace -scheme Wire-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          xcodebuild build -project Wire-iOS.xcodeproj -scheme Wire-iOS 
          

  testUI:  
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.ui == 'true' }}
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      
      - name: Select Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
      #- name: Fetch derive path from job one
      #  run: echo ${{needs.build.outputs.derivePath}}
      - name: Fetch dependencies
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./setup.sh
      - name: Build UI Tests
        run: |
          #xcodebuild build -workspace wire-ios.xcworkspace -scheme Wire-iOS
          xcodebuild build -workspace wire-ios.xcworkspace -scheme Wire-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
      - name: Run UI Tests
        run: |
          #xcodebuild test -project Wire-iOS.xcodeproj -scheme Wire-iOS -configuration Debug -derivedDataPath build
          xcodebuild test -workspace wire-ios.xcworkspace -scheme Wire-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
      
  testSyncEngine:  
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.syncEngine == 'true' }}
    runs-on: macos-latest
    
      
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
      #- name: Fetch derive path from job one
      #  run: echo ${{needs.build.outputs.derivePath}}
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For Sync Engine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireSyncEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For Sync Engine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireSyncEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
     
  testDataModel:  
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.dataModel == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
      #- name: Fetch derive path from job one
      #  run: echo ${{needs.build.outputs.derivePath}}
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For Sync Engine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireDataModel -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For Sync Engine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireDataModel -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty

  testWireRequestStrategy:  
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.requestStrategy == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For Sync Engine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireRequestStrategy -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For Sync Engine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireRequestStrategy -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireSystem:  
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.iosSystem == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For Sync Engine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireSystem -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For Sync Engine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireSystem -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireTransport:
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.transport == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For Sync Engine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For Sync Engine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireShareEngine:
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.shareEngine == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For Sync Engine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireShareEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For Sync Engine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireShareEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireCryptobox:
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.cryptobox == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For cryptobox
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireCryptobox -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For cryptobox
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireCryptobox -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireMockTransport:
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.mockTransport == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For mockTransport
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireMockTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For mockTransport
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireMockTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireNotificationEngine:
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.notificationEngine == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For notificationEngine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireNotificationEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For notificationEngine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireNotificationEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireImages:
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.wireImages == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For wireImages
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireImages -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For wireImages
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireImages -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireLinkPreview:
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.linkPreview == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For Sync Engine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireLinkPreview -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For Sync Engine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireLinkPreview -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
  testWireUtilities:
    needs: 
      - build
      - changes

    if: ${{ needs.changes.outputs.utilities == 'true' }}
    runs-on: macos-latest
    
    steps:
    - name: Fetch derive path from job one
      run: echo ${{needs.build.outputs.derivePath}}
      
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
      
    - name: Select Xcode
      run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
    - name: Fetch dependencies
      env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./setup.sh
    - name: Build UI Tests For Sync Engine
      run: |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireUtilities -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          
    - name: Run UI Tests For Sync Engine
      run: |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireUtilities -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
     
