name: buildtestAp2

on:
  pull_request:
    branches: [ "develop" ]
      
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      ui: ${{ steps.filter.outputs.ui }}
      syncEngine: ${{ steps.filter.outputs.syncEngine }}
      dataModel: ${{ steps.filter.outputs.dataModel }}
      system: ${{ steps.filter.outputs.system }}
      requestStrategy: ${{ steps.filter.outputs.requestStrategy }}
      transport: ${{ steps.filter.outputs.transport }}
      shareEngine: ${{ steps.filter.outputs.shareEngine }}
      cryptobox: ${{ steps.filter.outputs.cryptobox }}
      mockTransport: ${{ steps.filter.outputs.mockTransport }}
      notificationEngine: ${{ steps.filter.outputs.notificationEngine }}
      protos: ${{ steps.filter.outputs.protos }}
      images: ${{ steps.filter.outputs.images }}
      linkPreview : ${{ steps.filter.outputs.linkPreview }}
      utilities: ${{ steps.filter.outputs.utilities }}
      testing : ${{ steps.filter.outputs.testing }}
      
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          ui:
            - 'wire-ios/**'
          syncEngine:
            - 'wire-ios-sync-engine/**'
          dataModel:
            - 'wire-ios-data-model/**'
          system:
            - 'wire-ios-system/**'
          requestStrategy:
            - 'wire-ios-request-strategy/**'
          transport:
            - 'wire-ios-transport/**'
          shareEngine:
            - 'wire-ios-share-engine/**'
          cryptobox:
            - 'wire-ios-cryptobox/**'
          mockTransport:
            - 'wire-ios-mock-transport/**'
          notificationEngine:
            - 'wire-ios-notification-engine/**'
          protos:
            -  'wire-ios-protos/**'
          images:
            - 'wire-ios-images/**'
          linkPreview:
            - 'wire-ios-link-preview/**'
          utilities:
            - 'wire-ios-utilities/**'  
          testing:
            - 'wire-ios-testing/**'  
            
  buildAndTest:
    needs: changes
    runs-on: macOS-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      
      - name: Select Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
      - name: Fetch dependencies
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./setup.sh
        
      - name: WireSystem
        if: ${{ needs.changes.outputs.system == 'true' }}
        run: |
          echo "WireSystem has changes" |
          echo "Building WireSystem..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireSystem -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireSystem..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireSystem -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireTesting
        if: ${{ needs.changes.outputs.testing == 'true' }}
        run: |
          echo "WireTesting has changes" |
          echo "Fetching dependencies for WireTesting..." |
          cd wire-ios-testing |
          carthage bootstrap --platform ios --use-xcframeworks |
          cd .. |
          echo "Building WireTesting..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireTesting -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireTesting..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireTesting -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireUtilities
        if: ${{ needs.changes.outputs.utilities == 'true' }}
        run: |
          echo "WireUtilities has changes" |
          echo "Building WireUtilities..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireUtilities -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireUtilities..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireUtilities -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireCryptobox
        if: ${{ needs.changes.outputs.cryptobox == 'true' }}
        run: |
          echo "WireCryptobox has changes" |
          echo "Fetching dependencies for WireCryptobox..." |
          cd wire-ios-cryptobox |
          carthage bootstrap --platform ios --use-xcframeworks |
          cd .. |
          echo "Building WireCryptobox..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireCryptobox -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireCryptobox..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireCryptobox -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireTransport
        if: ${{ needs.changes.outputs.transport == 'true' }}
        run: |
          echo "WireTransport has changes" |
          echo "Fetching dependencies for WireTransport..." |
          cd wire-ios-transport |
          carthage bootstrap --platform ios --use-xcframeworks |
          cd .. |
          echo "Building WireTransport..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireTransport..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireLinkPreview
        if: ${{ needs.changes.outputs.linkPreview == 'true' }}
        run: |
          echo "WireLinkPreview has changes" |
          echo "Fetching dependencies for WireLinkPreview..." |
          cd wire-ios-link-preview |
          carthage bootstrap --platform ios --use-xcframeworks |
          cd .. |
          echo "Building WireLinkPreview..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireLinkPreview -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireLinkPreview..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireLinkPreview -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireImages
        if: ${{ needs.changes.outputs.images == 'true' }}
        run: |
          echo "WireImages has changes" |
          echo "Building WireTesting..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireTesting -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Building WireImages..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireImages -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireImages..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireImages -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}          

      - name: WireProtos
        if: ${{ needs.changes.outputs.protos == 'true' }}
        run: |
          echo "WireProtos has changes" |
          echo "Fetching dependencies for WireProtos..." |
          cd wire-ios-protos |
          carthage bootstrap --platform ios --use-xcframeworks |
          cd .. |
          echo "Building WireProtos..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireProtos -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireProtos..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireProtos -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}          
          
      - name: WireMockTransport
        if: ${{ needs.changes.outputs.mockTransport == 'true' }}
        run: |
          echo "WireMockTransport has changes" |
          echo "Building WireMockTransport..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireMockTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireMockTransport..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireMockTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireDataModel
        if: ${{ needs.changes.outputs.dataModel == 'true' }}
        run: |
          echo "WireDataModel has changes" |
          echo "Fetching dependencies for WireDataModel..." |
          cd wire-ios-data-model |
          carthage bootstrap --platform ios --use-xcframeworks |
          cd .. |
          echo "Building WireDataModel..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireDataModel -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireDataModel..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireDataModel -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireRequestStrategy
        if: ${{ needs.changes.outputs.requestStrategy == 'true' }}
        run: |
          echo "WireRequestStrategy has changes" |
          echo "Building WireRequestStrategy..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireRequestStrategy -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireRequestStrategy..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireRequestStrategy -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireNotificationEngine
        if: ${{ needs.changes.outputs.notificationEngine == 'true' }}
        run: |
          echo "WireNotificationEngine has changes" |
          echo "Fetching dependencies for WireNotificationEngine..." |
          echo "Building WireTesting..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireTesting -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Building WireNotificationEngine..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireNotificationEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireNotificationEngine..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireNotificationEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}

      - name: WireShareEngine
        if: ${{ needs.changes.outputs.shareEngine == 'true' }}
        run: |
          echo "WireShareEngine has changes" |
          echo "Building WireShareEngine..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireShareEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireShareEngine..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireShareEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}

      - name: WireSyncEngine
        if: ${{ needs.changes.outputs.syncEngine == 'true' }}
        run: |
          echo "WireSyncEngine has changes" |
          echo "Fetching dependencies for WireSyncEngine..." |
          cd wire-ios-sync-engine |
          carthage bootstrap --platform ios --use-xcframeworks |
          cd .. |
          echo "Building WireSyncEngine..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireSyncEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireSyncEngine..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireSyncEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
          
      - name: WireUI
        if: ${{ needs.changes.outputs.ui == 'true' }}
        run: |
          echo "WireUI has any changes ?" |
          echo "Setting up WireUI..." |
          cd wire-ios |
          ./setup.sh |
          cd .. |
          echo "Building WireUI..." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme Wire-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          echo "Testing WireUI..." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme Wire-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty
          exit ${PIPESTATUS[0]}
      
