name: buildtestAp2

on:
  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'wire-ios/**'
      
jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      ui: ${{ steps.filter.outputs.ui }}
      syncEngine: ${{ steps.filter.outputs.syncEngine }}
      dataModel: ${{ steps.filter.outputs.dataModel }}
      iosSystem: ${{ steps.filter.outputs.iosSystem }}
      requestStrategy: ${{ steps.filter.outputs.requestStrategy }}
      transport: ${{ steps.filter.outputs.transport }}
      shareEngine: ${{ steps.filter.outputs.shareEngine }}
      cryptobox: ${{ steps.filter.outputs.cryptobox }}
      mockTransport: ${{ steps.filter.outputs.mockTransport }}
      notificationEngine: ${{ steps.filter.outputs.notificationEngine }}
      wireImages: ${{ steps.filter.outputs.wireImages }}
      utilities: ${{ steps.filter.outputs.utilities }}
      wireTesting : ${{ steps.filter.outputs.utilities }}
      
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          ui:
            - 'wire-ios/**'
          syncEngine:
            - 'wire-ios-sync-engine/**'
          dataModel:
            - 'wire-ios-data-model/**'
          iosSystem:
            - 'wire-ios-system/**'
          requestStrategy:
            - 'wire-ios-request-strategy/**'
          transport:
            - 'wire-ios-transport/**'
          shareEngine:
            - 'wire-ios-share-engine/**'
          cryptobox:
            - 'wire-ios-cryptobox/**'
          mockTransport:
            - 'wire-ios-mock-transport/**'
          notificationEngine:
            - 'wire-ios-notification-engine/**'
          wireImages:
            - 'wire-ios-images/**'
          utilities:
            - 'wire-ios-utilities/**'  
          wireTesting:
            - 'wire-ios-testing/**'  
  buildAndTest:
    needs: changes
    env:
      derivePath: "DerivedData"
    
    runs-on: macOS-latest
      
    steps:
      - uses: actions/checkout@v3
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
      
      - name: Select Xcode
        run: |
          sudo xcode-select -switch /Applications/Xcode_13.1.app
          /usr/bin/xcodebuild -version
      - name: Fetch dependencies
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./setup.sh
      - name: Any chnages in UI project ?
        if: ${{ needs.changes.outputs.ui == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireDataModel -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' -derivedDataPath $derivePath | xcpretty
          xcodebuild build -workspace wire-ios.xcworkspace -scheme WireSyncEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' -derivedDataPath $derivePath | xcpretty
          xcodebuild build -workspace wire-ios.xcworkspace -scheme Wire-iOS -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' -derivedDataPath $derivePath | xcpretty
          exit ${PIPESTATUS[0]}
      
      - name: Any changes in WireSyncEngine project ?
        if: ${{ needs.changes.outputs.syncEngine == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireSyncEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' -derivedDataPath $derivePath | xcpretty
  
      - name: Any changes in WireDataModel project ?
        if: ${{ needs.changes.outputs.dataModel == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireDataModel -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' -derivedDataPath $derivePath | xcpretty

      - name: Any changes in WireSystem project ?
        if: ${{ needs.changes.outputs.iosSystem == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireSystem -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' -derivedDataPath $derivePath | xcpretty
     
      - name: Any changes in WireNotificationEngine project ?
        if: ${{ needs.changes.outputs.notificationEngine == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireNotificationEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' -derivedDataPath $derivePath | xcpretty
          
      - name: Any changes in WireImages project ?
        if: ${{ needs.changes.outputs.wireImages == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireImages -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0'  -derivedDataPath $derivePath | xcpretty
      
      - name: Any changes in WireRequestStrategy project ?
        if: ${{ needs.changes.outputs.requestStrategy == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireRequestStrategy -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0'  -derivedDataPath $derivePath | xcpretty
      
      - name: Any changes in WireTesting project ?
        if: ${{ needs.changes.outputs.wireTesting == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireTesting -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0'  -derivedDataPath $derivePath | xcpretty
      
      - name: Any changes in WireTransport project ?
        if: ${{ needs.changes.outputs.transport == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireTransport -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0'  -derivedDataPath $derivePath | xcpretty
      
      - name: Any changes in WireShareEngine project ?
        if: ${{ needs.changes.outputs.shareEngine == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireShareEngine -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0'  -derivedDataPath $derivePath | xcpretty
      
      - name: Any changes in WireCryptobox project ?
        if: ${{ needs.changes.outputs.cryptobox == 'true' }}
        run: |
          echo "Yes, changes are there.." |
          xcodebuild test -workspace wire-ios.xcworkspace -scheme WireCryptobox -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0'  -derivedDataPath $derivePath | xcpretty
      
