name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

