name: Paths test

on:
  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'wire-ios/**'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Echo
      run: echo "hello world"
