name: Paths test

on:
  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'wire-ios/**'

jobs:
  one:
    runs-on: macos-latest

    steps:
    - name: Echo
      run: echo "hello world"

  two:
    needs: one
    runs-on: macos-latest

    steps:
    - name: Echo
      run: echo "goodbye world"
