name: Paths test

on:
  pull_request:
    branches: [ "develop" ]
    paths: 
      - 'wire-ios/**'

env:
  derivePath: Hello JJ
  
jobs:
  one:
    runs-on: macos-latest
    
    outputs:
      output1: 'ios/wire-ios/build'
      
    env:
      derivePath: 'ios/wire-ios/build'
    
    steps:
    - name: Echo
      run: echo "hello world"
    - name: Set derive path in job one
      run: echo "Derive Path is $derivePath"
      

  two:
    needs: one
    runs-on: macos-latest

    steps:
    - name: Echo
      run: echo "goodbye world"
    - name: Fetch derive path from job one
      run: echo ${{needs.one.outputs.output1}}
