name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Filtering path
        run: echo 'Filtering path to extract framework'
      - uses: actions/checkout@v2.1.0
      - run: |
          mapfile -t changed_files < <(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          printf 'changed file: %s\n' ${changed_files[*]}
    
        
        
